services:
  psyonic_plotting_tools:
    container_name: psyonic_plotting_tools
    working_dir: /
    build:
      dockerfile: Dockerfile
      network: host
    network_mode: host
    privileged: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/Tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock