version: '3.8'

services:
  psyonic-plotting:
    build: .
    container_name: psyonic-plotting-test
    volumes:
      # Mount the current directory to allow easy testing of script changes
      - .:/app
      # Mount /dev to allow access to serial ports if needed
      - /dev:/dev
    environment:
      - MPLBACKEND=Agg
    # Run the test script by default
    command: ./test_requirements.sh
    # Alternative: uncomment the line below to run the actual calibration script
    # command: ./run_calibration_plot.sh 