# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['plot_lines.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'matplotlib',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.backends.backend_qt5agg', 
        'matplotlib.backends.backend_gtk3agg',
        'matplotlib.backends.backend_wxagg',
        'matplotlib.animation',
        'matplotlib.pyplot',
        'matplotlib.figure',
        'matplotlib.axes',
        'matplotlib.backends.backend_agg',
        'numpy',
        'numpy.core._methods',
        'numpy.lib.format',
        'serial',
        'serial.tools.list_ports',
        'serial.tools.list_ports_common',
        'serial.tools.list_ports_posix',
        'serial.tools.list_ports_windows',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='plot-lines',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
) 